projects:

  - title: werds.co
    image_url: /assets/img/werds.co.gif
    live_link: https://werds.co
    description: 'A place for words. Try it: <form action="https://werds.co" method="get"><input type="text" name="t"/><button type="submit" style="display:none;"></form>'

  - title: Triangulunch
    image_url: /assets/img/triangulun.ch.gif
    live_link: https://triangulun.ch/
    description: Meet in the middle for lunch!

  - title: Slink
    image_url: /assets/img/slink.gif
    live_link: http://www.slink.chat
    description: An AIM clone visually influenced by Windows 95. Built on <a href="http://rubyonrails.org/" target="_blank">Rails</a>, <a href="https://www.postgresql.org/" target="_blank">PostgreSQL</a>, <a href="https://facebook.github.io/react/" target="_blank">React</a>, and <a href="http://redux.js.org/" target="_blank">Redux</a>.

  - title: Primordial Playground
    image_url: /assets/img/primordial-playground.gif
    live_link: https://broothie.github.io/primordial-playground/
    description: A colorful, interactive Game of Life sandbox. Built with <a href="https://www.javascript.com">vanilla js</a>.
